# Generated by scripts/books_read_grouped.sh
# Input rows: shelf | date | stars | pages | title | author

function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }

function stars(n,    i, out) {
  out = ""
  for (i = 0; i < n; i++) out = out "★"
  return out
}

BEGIN {
  print "-# Generated file. Do not edit."
  print "-# Source: src/data/books (read shelf)."
  print ""
  prev_year = ""
}

{
  shelf = trim($1)
  date = trim($2)
  rating = trim($3) + 0
  title = trim($5)
  author = trim($6)

  if (shelf != "read") next
  year = substr(date, 1, 4)
  if (year == "") next

  if (year != prev_year) {
    if (prev_year != "") print ""
    print "h3.year"
    print "  | " year
    print "ol.book_list"
    prev_year = year
  }

  print "  li"
  print "    span.book"
  print "      | " title
  print "    | "
  print ""
  print "    span.author"
  print "      | — " author

  meta = "(" date
  if (rating > 0) meta = meta " · " stars(rating)
  meta = meta ")"

  print "    | "
  print ""
  print "    span.meta"
  print "      | " meta
}
